### ISSUE TITLE
run time stamp

### ISSUE THREAD

**Issue by rdewijn** [tercen/ps12image_operator#4]
Which tag can be used as the run identifier?

**Comment by ginberg** [comment]
@fnaji isn't this the protocol ID?

**Comment by fnaji** [comment]
yes, please rename  Protocol ID  to "Run ID"

**Comment by amaurel** [comment]
Correct spelling is RunId

**Comment by amaurel** [comment]
In BN we can find

dimensionNames
	| aList |
	aList := OrderedCollection new.
	aList add: 'Barcode'.
	aList add: 'Row'.
	aList add: 'Col'.
	aList add: 'Filter'.
	aList add: 'Cycle'.
	aList add: 'Exposure time'.
	aList add: 'Image'.
	aList add: 'Temperature'.
	aList add: 'Instrument type'.
	aList add: 'Instrument unit'.
	aList add: 'Image timestamp'.
	aList add: 'RunId'.
	aList addAll: properties keys asSortedCollection.
	^aList

**Comment by ginberg** [comment]
Protocol ID has been renamed in latest version
